
references:
  simple: &simple
    docker:
      - image: cumuluss/circleci:node-8.11
    working_directory: ~/project

  localstack: &localstack
    docker:
      - image: cumuluss/circleci:node-8.11
      - name: localstack
        image: localstack/localstack:0.8.7
        environment:
          ENV_INTERNAL_TEST_RUN: true
          DEBUG: 1
          SERVICES: 'kinesis,lambda,s3,sns,sqs,dynamodb,dynamodbstreams'
      - name: elastichost
        image: elasticsearch:5.6
        environment:
          # limit memory usage to 750mb
          ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    working_directory: ~/project
  
  restore_package_cache: &restore_package_cache
    restore_cache:
      keys:
        - cumulus-packages-{{ checksum "global-hash" }}

  attach_workspace: &attach_workspace
    attach_workspace:
      # Must be absolute path or relative path from working_directory
      at: /home/circleci/project

  server: &server
    run:
      name: Restore workspace data
      command: |
        ./bin/restore_cache
        # start ftp
        sudo rm -rf /home/vsftpd
        sudo ln -s /home/circleci/project/packages/test-data /home/vsftpd
        sudo service vsftpd start || true

        # start http service
        sudo rm -rf /var/www/html
        sudo ln -s /home/circleci/project/packages/test-data /var/www/html
        sudo service apache2 start

        # start sftp service
        sudo bash /usr/sbin/sftp.sh user:password
        sudo cp -r /home/circleci/project/packages/test-data/* /home/user/
        sudo cp -r /home/circleci/project/packages/test-data/keys /home/user/.ssh

        mkdir .final_nyc_output

version: 2
jobs:
  install:
    <<: *simple
    steps:
      - checkout
      - restore_cache:
          keys:
            - core-{{ checksum "lerna.json" }}-{{ checksum "package.json" }}
            - core-

      - run:
          name: core installation
          command: |
            yarn

            # generate global hash
            ./node_modules/.bin/lerna exec --concurrency 1 -- sha1sum package.json | awk '{print $1}' '' >> /home/circleci/project/global-hash

      - save_cache:
          paths:
            - ./node_modules
          key: core-{{ checksum "lerna.json" }}-{{ checksum "package.json" }}

      - *restore_package_cache 

      - run:
          name: Installing Dependencies
          command: |
            # restore cache
            ./bin/restore_cache
            yarn bootstrap-no-build
            # save_cache
            ./bin/save_cache

      - save_cache:
          key: cumulus-packages-{{ checksum "global-hash" }}
          paths:
            - ./circleci_cache

      - persist_to_workspace:
          root: /home/circleci/project 
          # Must be relative path from root
          paths:
            - global-hash
            - node_modules

  non_api_tests:
    <<: *localstack
    steps:
      - checkout
      - *attach_workspace
      - *restore_package_cache
      - *server 
      
      - run:
          name: Running eslint
          command: ./node_modules/.bin/eslint packages/api --ext .js

      - run:
          name: Running All Tests except API
          environment:
            LOCALSTACK_HOST: localstack
            LOCAL_ES_HOST: elastichost
          command: ./node_modules/.bin/nyc ./node_modules/.bin/lerna run test --concurrency 2 --ignore @cumulus/api
      
      - run:
          name: Running End to End Tests
          environment:
            LOCALSTACK_HOST: localstack
          command: yarn e2e

  api_endpoints_tests:
    <<: *localstack
    steps:
      - checkout
      - *attach_workspace
      - *restore_package_cache
      - *server 
      - run:
          name: Running API endpoint Tests
          environment:
            LOCALSTACK_HOST: localstack
            LOCAL_ES_HOST: elastichost
          command: |
            cd packages/api
            ./node_modules/.bin/nyc ./node_modules/.bin/ava tests/endpoints/*.js
            cp .nyc_output/* ../../.final_nyc_output

      - run:
          name: Running API ES Tests
          environment:
            LOCALSTACK_HOST: localstack
            LOCAL_ES_HOST: elastichost
          command: |
            cd packages/api
            ./node_modules/.bin/nyc ./node_modules/.bin/ava tests/es/*.js
            cp .nyc_output/* ../../.final_nyc_output

      - run:
          name: Running API migration Tests
          environment:
            LOCALSTACK_HOST: localstack
            LOCAL_ES_HOST: elastichost
          command: |
            cd packages/api
            ./node_modules/.bin/nyc ./node_modules/.bin/ava tests/migrations/*.js
            cp .nyc_output/* ../../.final_nyc_output

      - run:
          name: Running API Lambda Tests
          environment:
            LOCALSTACK_HOST: localstack
            LOCAL_ES_HOST: elastichost
          command: |
            cd packages/api
            ./node_modules/.bin/nyc ./node_modules/.bin/ava tests/lambdas/*.js
            cp .nyc_output/* ../../.final_nyc_output

      - run:
          name: Running API cli Tests
          environment:
            LOCALSTACK_HOST: localstack
            LOCAL_ES_HOST: elastichost
          command: |
            cd packages/api
            ./node_modules/.bin/nyc ./node_modules/.bin/ava tests/cli/*.js
            cp .nyc_output/* ../../.final_nyc_output

  build_from_source:
    <<: *simple
    steps:
      - checkout
      - *restore_package_cache
      - *attach_workspace
    
      - run:
          name: Prepare for Integration Tests
          environment:
            PRODUCTION: true # this will ensure that the integration from source uses the same packaging as the integration from npm packages
          command: |
            source ./example/spec/select

            if [[ ! -z "$RUN_INTEGRATION" ]]; then
              sudo chown -R circleci:circleci /usr/local/bin

              # install cumulus-integration
              ./bin/prepare
            fi

      - run:
          name: Deploy cumulus source code to aws
          command: |
            source ./example/spec/select
            if [[ ! -z "$RUN_INTEGRATION" ]]; then
              cd example

              # deploy latest iam roles to aws
              ./node_modules/.bin/kes cf deploy --kes-folder iam --region us-east-1 --deployment $DEPLOYMENT --template node_modules/@cumulus/deployment/iam

              # deploy latest version of the packages to the aws
              ./node_modules/.bin/kes cf deploy --kes-folder app --region us-east-1 --deployment $DEPLOYMENT --template node_modules/@cumulus/deployment/app && ./node_modules/.bin/kes lambda S3AccessTest deploy --kes-folder app --region us-west-1 --deployment $DEPLOYMENT --template node_modules/@cumulus/deployment/app
            fi

  integration_from_source:
    <<: *simple
    steps:
      - checkout
      - *restore_package_cache
      - *attach_workspace
      - run:
          name: Run AWS Integration tests 
          command: |
            source ./example/spec/select
            if [[ ! -z "$RUN_INTEGRATION" ]]; then
              cd example

              # run the tests
              echo $DEPLOYMENT
              yarn test
            fi

    
  generate_docs:
    <<: *simple
    steps:
      - checkout
      - *attach_workspace

      - run:
          name: Prepare Unreleased Docs
          command: |
            if [[  "$CIRCLE_BRANCH" == 'master' ]]; then
              yarn docs-build
              # mv _book unreleased
            fi
      
            - add_ssh_keys:
          fingerprints:
            - "ac:b8:9d:87:6b:65:ff:6f:a1:7c:42:c5:3c:2f:39:93"
      
      - run:
          name: Publish Documentation
          command: |
            if [[  "$CIRCLE_BRANCH" == 'master' ]]; then
              cd _book
              git init
              git config user.name "Devseed"
              git config user.email "info@developmentseed.org"
              git add -A
              git commit -m "Automated build in circleci"
              git push --force --quiet git@github.com:nasa/cumulus master:gh-pages
              rm -rf .git
            fi


workflows:
  version: 2
  cumulus:
    jobs:
      - install
      - non_api_tests:
          requires:
            - install
      - api_tests:
          requires:
            - install
      # - api_es_tests:
      #     requires:
      #       - install 
      # - api_migration_tests:
      #     requires:
      #       - install
      # - api_lambda_tests:
      #     requires:
      #       - install
      # - api_cli_tests:
      #     requires:
      #       - install
      - build_from_source:
          requires:
            - install
      - integration_from_source:
          requires:
            - build_from_source
      - generate_docs:
          requires:
            - install
